name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-exe:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        if exist requirements.txt pip install -r requirements.txt

    - name: Unzip source
      run: |
        mkdir source
        tar -xf observability_demo_final_source.zip -C source

    - name: Build EXE with PyInstaller
      run: |
        pip install pyinstaller
        cd source
        pyinstaller --onefile __main__.py

    - name: Upload EXE artifact
      uses: actions/upload-artifact@v3
      with:
        name: observability-demo-exe
        path: source/dist/*.exe
